databases:
  - name: nexus-db
    databaseName: nexus
    user: nexus_user

services:
  - type: web
    name: nexus-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    rootDir: "backend"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com"
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_PUBLIC_URL
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.9
